### ISSUE TITLE
App that handle database migrations

### ISSUE THREAD

**Issue by maxneuvians** [cds-snc/github-repository-quality-index#28]
We need an app that handles all the database migrations separate of the app logic

**Comment by willeybryan** [comment]
- Migrate to PostgreSQL db
- For config and setup this is the code that will build the db to the schema the app supports

**Comment by timarney** [comment]
Scripts are setup in the "DB" dir

```
npm run start
```

Will create the database defined in the .env file + create the table schema

```
npm run migrate
```

Will run the migrations as need be

**Comment by maxneuvians** [comment]
Closed in https://github.com/cds-snc/github-repository-quality-index/commit/89197de12cf95a036f02e70bd890010c381b316f
