### ISSUE TITLE
Agent app needs to deploy to Google cloud run

### ISSUE THREAD

**Issue by maxneuvians** [cds-snc/github-repository-quality-index#30]
We need to add CD for the agent to deploy to cloud run

**Comment by willeybryan** [comment]
Agent is the thing that collects the info from a Github Repo. Needs to sit in GCP so we can call it when we need it.

**Comment by maxneuvians** [comment]
Closed in https://github.com/cds-snc/github-repository-quality-index/commit/5ad9701834f25ba7105de5559144f530c7c869ca
