### ISSUE TITLE
Charting app

### ISSUE THREAD

**Issue by maxneuvians** [cds-snc/github-repository-quality-index#33]
Need an app that shows all the scores for a particular repo over time and also aggregates all the scores and shows them over time

**Comment by timarney** [comment]
This is setup in the `charts` dir

Docker file needs to be updated to share the db models etc... going to make a new issue for that.

**Usage:**
http://the-server/?reponame=digital-canada-ca

**Dev:**
```
yarn start
```

Visit:
http://localhost:1234/?reponame=digital-canada-ca

Database is already seeded with data for digital-canada-ca
