### ISSUE TITLE
Generate fake data for DB

### ISSUE THREAD

**Issue by maxneuvians** [cds-snc/github-repository-quality-index#35]
Codifying the TSS may block building the charting app. We can just add dummy data for the charting app now. Same data should look like this:
```
{
id: n
system: tss
repoName: test
score: {
   value: something between 100 - 500 ex. 355
   clarity: 0 - 1 ex. 0.34
   ambiguity: 0 - 1 ex. 0.25
} 
insertedAt: Date
}
```
Ideally we would be able to specify the number of days and the number of repos. So number of days would generate an entry for each day for a number of repos. The scores can be totally randomized.  ex. 50 days for 10 repos would create 500 entries, 50 for each.

**Comment by timarney** [comment]
Script is setup to do this in the `faker` dir.  The output of that script can be pasted into the seed file to seed the db (https://github.com/cds-snc/github-repository-quality-index/commit/71ff421b72645995245e86dccc4bca75150775d0).
